export const ADD_INVENTORY = "ADD_INVENTORY";
export const REMOVE_INVENTORY = "REMOVE_INVENTORY";
export const SET_INVENTORY = "SET_INVENTORY";
export const INIT_INVENTORY = "INIT_INVENTORY";
export const FETCH_INVENTORY_FAILED = "FETCH_INVENTORY_FAILED";
export const SET_LIST = "SET_LIST";
export const FETCH_LIST_FAILED = "FETCH_LIST_FAILED";
export const INIT_LIST = "INIT_LIST";
export const SET_PRICES = "SET_PRICES";
export const FETCH_PRICES_FAILED = "FETCH_PRICES_FAILED";
export const INIT_PRICES = "INIT_PRICES";
export const SHOW_CART_DRAWER = "SHOW_CART_DRAWER";
export const EMPTY_SHOP_CART = "EMPTY_SHOP_CART";

export const PURCHASE_INVENTORY = "PURCHASE_INVENTORY";
export const PURCHASE_INVENTORY_START = "PURCHASE_INVENTORY_START";
export const PURCHASE_INVENTORY_SUCCESS = "PURCHASE_INVENTORY_SUCCESS";
export const PURCHASE_INVENTORY_FAIL = "PURCHASE_INVENTORY_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
