export const ADD_INVENTORY = "ADD_INVENTORY";
export const REMOVE_INVENTORY = "REMOVE_INVENTORY";
export const SET_INVENTORY = "SET_INVENTORY";
export const INIT_INVENTORY = "INIT_INVENTORY";
export const FETCH_INVENTORY_FAILED = "FETCH_INVENTORY_FAILED";
export const SET_LIST = "SET_LIST";
export const FETCH_LIST_FAILED = "FETCH_LIST_FAILED";
export const INIT_LIST = "INIT_LIST";

export const PURCHASE_BURGER = "PURCHASE_BURGER";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
