export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INVENTORY = "SET_INVENTORY";
export const FETCH_INVENTORY_FAILED = "FETCH_INVENTORY_FAILED";
export const SET_LIST = "SET_LIST";
export const FETCH_LIST_FAILED = "FETCH_LIST_FAILED";

export const PURCHASE_STORE_START = "PURCHASE_STORE_START";
export const PURCHASE_STORE_SUCCESS = "PURCHASE_STORE_SUCCESS";
export const PURCHASE_STORE_FAIL = "PURCHASE_STORE_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
